apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shopping
spec:
  destination:
    name: ''
    namespace: webtier
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 12.1.25
    chart: wordpress
    helm:
      parameters:
        - name: wordpressUsername
          value: admin
        - name: wordpressPassword
          value: Embe1mpls
        - name: wordpressEmail
          value: roshpr@juniper.net
        - name: wordpressFirstName
          value: Admin
        - name: wordpressLastName
          value: Shop
        - name: wordpressBlogName
          value: Shop Away!
        - name: service.type
          value: NodePort
        - name: persistence.enabled
          value: 'false'
        - name: mariadb.enabled
          value: 'false'
        - name: externalDatabase.host
          value: shopdatabase-mariadb.dbtier.svc.cluster.local
        - name: externalDatabase.password
          value: Embe1mpls
        - name: externalDatabase.user
          value: admin
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
