apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cn2-app
  namespace: argocd
spec:
  destination:
    namespace: default
    name: in-cluster
  project: default
  source:
    path: demo
    repoURL: https://github.com/Juniper/contrail-pipelines.git
    targetRevision: HEAD
