apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: contrail-test-app
  namespace: argocd
spec:
  destination:
    namespace: default
    name: in-cluster
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true  
  source:
    path: test_infra_setup
    repoURL: https://github.com/Juniper/contrail-pipelines
    targetRevision: HEAD
