apiVersion: v1
kind: Pod
metadata:
  name: pod2
  annotations:
    k8s.v1.cni.cncf.io/networks: vn2
spec:
  nodeSelector:
    node-role.kubernetes.io/master: ""
  imagePullSecrets:
  - name: svl-artifactory
  tolerations:
  - effect: NoSchedule
    operator: Exists
  - effect: NoExecute
    operator: Exists
  containers:
  - name: busy1
    image: svl-artifactory.juniper.net/atom-docker/cn2/busybox
    command: ["/bin/sh","-c", "while true; do echo hello; sleep 10;done"]
    securityContext:
      privileged: true
