apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - name: busy1
    image: svl-artifactory.juniper.net/atom-docker/cn2/busybox
    command: ["/bin/sh","-c", "while true; do echo hello; sleep 10;done"]
    securityContext:
      privileged: true
